### ISSUE TITLE
darkfibook deployed version old ?

### ISSUE THREAD

**Issue by narodnik-intern** [darkrenaissance/darkfi#108]
the current deployed version of docs (https://darkrenaissance.github.io/darkfi/index.html) looks different than the master branch

![image](https://user-images.githubusercontent.com/114783613/193424282-28f0f0cf-f606-4c41-aa6c-7da4242adbca.png) 

![image](https://user-images.githubusercontent.com/114783613/193424373-9af7da9d-4125-4e61-aa80-515be4206d56.png)

**Comment by narodnik-intern** [comment]
`echo source $(pwd)/contrib/auto-complete >> ~/.bashrc` 

the missing $ symbol

**Comment by narodnik-intern** [comment]
fk 😑 🔫 , just adding \$ was the issue , addressed in #113

**Comment by narodnik** [comment]
It takes time also for redeployment to come into effect.
