### ISSUE TITLE
add rust stable version 1.64.0 as a prerequisite to the DOCS

### ISSUE THREAD

**Issue by narodnik-intern** [darkrenaissance/darkfi#109]
tried running ircd on ubuntu , works fine

but on MacOS M1 gives the following error after running the $make

rustc --version
rustc 1.59.0 (9d1b2106e 2022-02-23)

error ::
`% make           
RUSTFLAGS="" cargo build --all-features --release --package zkas
   Compiling darkfi v0.3.0 (/Users/user1/Desktop/darkfi)
error[E0599]: the method as_display exists for reference &ErrorKind, but its trait bounds were not satisfied
   --> src/error.rs:265:13
    |
265 |     #[error("IO error: {0}")]
    |             ^^^^^^^^^^^^^^^ method cannot be called on &ErrorKind due to unsatisfied trait bounds
    |
   ::: /Users/user1/.rustup/toolchains/1.59.0-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/io/error.rs:95:1
    |
95  | pub enum ErrorKind {
    | ------------------ doesn't satisfy ErrorKind: std::fmt::Display
    |
    = note: the following trait bounds were not satisfied:
            ErrorKind: std::fmt::Display
            which is required by &ErrorKind: DisplayAsDisplay

error[E0599]: the method as_display exists for reference &ErrorKind, but its trait bounds were not satisfied
   --> src/error.rs:372:13
    |
372 |     #[error("IO error: {0}")]
    |             ^^^^^^^^^^^^^^^ method cannot be called on &ErrorKind due to unsatisfied trait bounds
    |
   ::: /Users/user1/.rustup/toolchains/1.59.0-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/io/error.rs:95:1
    |
95  | pub enum ErrorKind {
    | ------------------ doesn't satisfy ErrorKind: std::fmt::Display
    |
    = note: the following trait bounds were not satisfied:
            ErrorKind: std::fmt::Display`

**Comment by narodnik-intern** [comment]
let me know if you need any help in testing ...

**Comment by narodnik-intern** [comment]
now works fine after upgrading rust version : 1.64.0 , after seeing #106 
i guess we need to specify this as a prerequisite in the docs 
since for a month i was thinking still there is no support for MacOS  ....

**Comment by parazyd** [comment]
Added to doc. Thanks.
