### ISSUE TITLE
can't make tau

### ISSUE THREAD

**Issue by sch1z00** [darkrenaissance/darkfi#126]
on debian bullseye I have these errors:

error[E0425]: cannot find value `from_occurrences` in this scope
    --> bin/tau/tau-cli/src/main.rs:51:25
     |
51 |     #[clap(short, parse(from_occurrences))]
     |                         ^^^^^^^^^^^^^^^^ not found in this scope

...

error[E0599]: no method named `parse` found for struct `Arg` in the current scope
    --> bin/tau/tau-cli/src/main.rs:51:19
     |
51 |     #[clap(short, parse(from_occurrences))]
     |                   ^^^^^ this is an associated function, not a method
     |
     = note: found the following associated functions; to be used as methods, functions must have a `self` parameter
note: the candidate is defined in the trait `Parser`
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.0.29/src/derive.rs:81:5

**Comment by Dastan-glitch** [comment]
thanks for pointing this out, it is fixed now, though tau is not fully ready yet
