### ISSUE TITLE
Error selecting a version of clap

### ISSUE THREAD

**Issue by trentlarson** [darkrenaissance/darkfi#133]
I cannot get past the first `make` in [the instructions to join ircd](https://darkrenaissance.github.io/darkfi/misc/ircd/ircd.html):

```
$ make BINS=ircd
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C contrib/token all
make[1]: Nothing to be done for `all'.
RUSTFLAGS="" cargo build --all-features --release --package zkas
    Updating crates.io index
    Updating git repository `https://github.com/ertosns/dashu`
    Updating git repository `https://github.com/Dastan-glitch/rust-term-grid.git`
error: failed to select a version for the requirement `clap = "=4.0.32"`
candidate versions found which didn't match: 3.2.23, 3.2.22, 3.2.21, ...
location searched: crates.io index
required by package `zkas v0.3.0 (/Users/trent/dev/from-elsewhere/darkfi/bin/zkas)`
make: *** [zkas] Error 101
```

I'm using:
* rust 1.51.0
* MacBook M1

**Comment by aggstam** [comment]
Hey trentlarson,
There was a fix re: clap after you posted this issue: [commit](https://github.com/darkrenaissance/darkfi/commit/e6339b26272862c270765b39b202b35e687c1895)
Could you recheck if it also fixed on your side?
Also could you update your rust version to 1.66.1(latest stable)?

**Comment by trentlarson** [comment]
OK! Updating the source didn't work, but upgrading to a newer rust (1.67.0) got me past that.
