### ISSUE TITLE
import-secrets

### ISSUE THREAD

**Issue by noddytheboi** [darkrenaissance/darkfi#137]
Hey.I trying to import existing address generated on previous session to wallet,so how to actually do this?
`./drk wallet --import-secrets` asking me few keys,i paste one and looks like it imported but not stored because its keeping asking me key.
Maybe there is some misunderstood by me,but how to use same address on each sessions?  

version: 0.4.0
rustc: 1.67.0

**Comment by aggstam** [comment]
You don't have to reimport address, daemon reuses it. Secrets export/import makes sense only when you want to move wallet to another file/system.
Let me know if any other issue exist so we can close the ticket.

**Comment by noddytheboi** [comment]
thx,i got it.but if i'll erase all data,and rebuild from scracth with new wallet_db,how to import it manually?it would keeping asking key

**Comment by aggstam** [comment]
You have to export the secrets using:
`drk wallet --secrets`
That will print your secret key!
After that you use:
`drk wallet --import-secrets`
to import back into the wallet_db file.
