### ISSUE TITLE
Cant build

### ISSUE THREAD

**Issue by dieaster** [darkrenaissance/darkfi#139]
make -C contrib/token all
make[1]: Entering directory '/root/darkfi/contrib/token'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/root/darkfi/contrib/token'
make -C src/contract/money
make[1]: Entering directory '/root/darkfi/src/contract/money'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/root/darkfi/src/contract/money'
make -C src/contract/dao
make[1]: Entering directory '/root/darkfi/src/contract/dao'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/root/darkfi/src/contract/dao'
RUSTFLAGS="" cargo build --all-features --release --package drk
   Compiling signal-hook v0.3.14
   Compiling libsqlite3-sys v0.24.2
   Compiling num-integer v0.1.45
The following warnings were emitted during compilation:

warning: sqlcipher/sqlite3.c:26228:10: fatal error: openssl/rand.h: No such file or directory
warning: 26228 | #include <openssl/rand.h>
warning:       |          ^~~~~~~~~~~~~~~~
warning: compilation terminated.

error: failed to run custom build command for `libsqlite3-sys v0.24.2`

Caused by:
  process didn't exit successfully: `/root/darkfi/target/release/build/libsqlite3-sys-7ee0f30090e1b1fe/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=sqlcipher/sqlite3.c
  cargo:rerun-if-changed=sqlite3/wasm32-wasi-vfs.c
  cargo:rustc-link-lib=dylib=crypto
  cargo:rerun-if-env-changed=SQLITE_MAX_VARIABLE_NUMBER
  cargo:rerun-if-env-changed=SQLITE_MAX_EXPR_DEPTH
  cargo:rerun-if-env-changed=LIBSQLITE3_FLAGS
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  CC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  CC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-DSQLITE_CORE" "-DSQLITE_DEFAULT_FOREIGN_KEYS=1" "-DSQLITE_ENABLE_API_ARMOR" "-DSQLITE_ENABLE_COLUMN_METADATA" "-DSQLITE_ENABLE_DBSTAT_VTAB" "-DSQLITE_ENABLE_FTS3" "-DSQLITE_ENABLE_FTS3_PARENTHESIS" "-DSQLITE_ENABLE_FTS5" "-DSQLITE_ENABLE_JSON1" "-DSQLITE_ENABLE_LOAD_EXTENSION=1" "-DSQLITE_ENABLE_MEMORY_MANAGEMENT" "-DSQLITE_ENABLE_RTREE" "-DSQLITE_ENABLE_STAT2" "-DSQLITE_ENABLE_STAT4" "-DSQLITE_SOUNDEX" "-DSQLITE_THREADSAFE=1" "-DSQLITE_USE_URI" "-DHAVE_USLEEP=1" "-D_POSIX_THREAD_SAFE_FUNCTIONS" "-DSQLITE_HAS_CODEC" "-DSQLITE_TEMP_STORE=2" "-DHAVE_ISNAN" "-DHAVE_LOCALTIME_R" "-DSQLITE_ENABLE_UNLOCK_NOTIFY" "-o" "/root/darkfi/target/release/build/libsqlite3-sys-78f63e774dc0e1ae/out/sqlcipher/sqlite3.o" "-c" "sqlcipher/sqlite3.c"
  cargo:warning=sqlcipher/sqlite3.c:26228:10: fatal error: openssl/rand.h: No such file or directory
  cargo:warning=26228 | #include <openssl/rand.h>
  cargo:warning=      |          ^~~~~~~~~~~~~~~~
  cargo:warning=compilation terminated.
  exit status: 1

  --- stderr

  error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-DSQLITE_CORE" "-DSQLITE_DEFAULT_FOREIGN_KEYS=1" "-DSQLITE_ENABLE_API_ARMOR" "-DSQLITE_ENABLE_COLUMN_METADATA" "-DSQLITE_ENABLE_DBSTAT_VTAB" "-DSQLITE_ENABLE_FTS3" "-DSQLITE_ENABLE_FTS3_PARENTHESIS" "-DSQLITE_ENABLE_FTS5" "-DSQLITE_ENABLE_JSON1" "-DSQLITE_ENABLE_LOAD_EXTENSION=1" "-DSQLITE_ENABLE_MEMORY_MANAGEMENT" "-DSQLITE_ENABLE_RTREE" "-DSQLITE_ENABLE_STAT2" "-DSQLITE_ENABLE_STAT4" "-DSQLITE_SOUNDEX" "-DSQLITE_THREADSAFE=1" "-DSQLITE_USE_URI" "-DHAVE_USLEEP=1" "-D_POSIX_THREAD_SAFE_FUNCTIONS" "-DSQLITE_HAS_CODEC" "-DSQLITE_TEMP_STORE=2" "-DHAVE_ISNAN" "-DHAVE_LOCALTIME_R" "-DSQLITE_ENABLE_UNLOCK_NOTIFY" "-o" "/root/darkfi/target/release/build/libsqlite3-sys-78f63e774dc0e1ae/out/sqlcipher/sqlite3.o" "-c" "sqlcipher/sqlite3.c" with args "cc" did not execute successfully (status code exit status: 1).

warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:52: drk] Error 101

**Comment by aggstam** [comment]
Verify that rust and all dependencies are installed.
Dependencies can be installed using the automated script by executing:
`sh contrib/dependency_setup`
Additionally, openssl seems to be missing, so you might need to install it by executing:
`apt install libssl-dev`
