### ISSUE TITLE
Configuration file with strange line

### ISSUE THREAD

**Issue by marek22k** [darkrenaissance/darkfi#142]
When I run `./darkfid` the first time, I get in line 64 of `~/.config/darkfi/darkfid_config.toml`: `sync_p2p_seed = ["tls:/lilith0.dark.fi:8342", "tls://lilith1.dark.fi:8342"]`. Shouldn't it be `sync_p2p_seed = ["tls://lilith0.dark.fi:8342", "tls://lilith1.dark.fi:8342"]` (two `/`)

**Comment by aggstam** [comment]
Hello, issue already fixed on commit [42109793b3e0f037a6a11e12a67fcbd1b362d483](https://github.com/darkrenaissance/darkfi/commit/42109793b3e0f037a6a11e12a67fcbd1b362d483)
