### ISSUE TITLE
error[E0463]: can't find crate for `core`

### ISSUE THREAD

**Issue by dan-da** [darkrenaissance/darkfi#159]
newbie here.  I got this error when trying to build ircd.

```
   Compiling proc-macro2 v1.0.50
error[E0463]: can't find crate for `core`
  |
  = note: the `wasm32-unknown-unknown` target may not be installed
  = help: consider downloading the target with `rustup target add wasm32-unknown-unknown`
```

The solution is:
```
rustup target add wasm32-unknown-unknown
```

That command is not present in the README, and the dependency_setup.sh does not run it on my system.

So I'm just filing this issue against the docs, to hopefully include it in the readme.

**Comment by aggstam** [comment]
Readme stated that you should install `wasm32-unknown-unknown`.
Rust toolchains are to managed by the user, like all development enviroments, so the command is somewhat redundant, but we added it so its clear.
dependency_setup.sh only install package dependencies.
