### ISSUE TITLE
Bitcoin deposit address

### ISSUE THREAD

**Issue by taxmeifyoucan** [darkrenaissance/darkfi#17]
Is there specific reason for using P2PKH addresses for deposits? `bitcoin` rust library offers P2wpkh, P2wsh formats. For this use case, LNP-BP might be useful https://github.com/LNP-BP/rust-lnpbp which also supports p2tr. 

In testnet setup, I see that after deposit, btc transaction is instantly sent to wallet `n3EvryUzcWNpJ6FRqmoxrRLytBar5GAQfC` which is reused many times. Is there any docs which would explain this process? It seems like unnecessary privacy leak.

**Comment by philippnagel** [comment]
I tried a quick search in the repo but it seems like the address isn't hardcoded. Would be great to get an explanation :)

**Comment by parazyd** [comment]
We started with such a design and it will be improved. If you read the code you can basically see what's going on in https://github.com/darkrenaissance/darkfi/blob/master/src/service/btc.rs

We'll see what we can do for the next steps.

**Comment by ghassmo** [comment]
we are switching to a new bridge for bitcoin
