### ISSUE TITLE
drk: build script doesn't enable optional dependency `play`

### ISSUE THREAD

**Issue by adoerr** [darkrenaissance/darkfi#175]
`cargo build -p drk`, will run into the error below:

![image](https://github.com/darkrenaissance/darkfi/assets/8516358/7aa619bb-7882-4d09-8433-2401dae7ff48)

Reason is that [this line in build.rs](https://github.com/darkrenaissance/darkfi/blob/029426fb6421f197b704a7963c63c491b0c0bbcd/bin/drk/build.rs#L24) will only enable the `play` feature for `rustc` but *not* the `cargo` optional dependency `play`. This seems to be expected behavior, please see [Features enabled through build scripts should have an effect on dependencies](https://github.com/rust-lang/cargo/issues/5499).

Please note that this error will not surface, if `make` is used since `make` implies `--all-features`. Doing a `make check`, however, will trigger the error.

Since according to the README, `libmpg123` is a required dependency anyway, we might want to make crate `play` a mandatory dependency for `drk`.

OTOH, the feature seems to be prone to causing issues (see #144), we might also consider to let the fun police :police_officer:  have it's way and remove the `play` feature. 

WDYT?

**Comment by parazyd** [comment]
I've implemented an alternative way to do it with `rodio`: https://github.com/darkrenaissance/darkfi/commit/88865e2663b5269e64317d13d1346645af057e66

Let me know if this works.

**Comment by adoerr** [comment]
I think the fix unfortunately has a new dependency

![image](https://github.com/darkrenaissance/darkfi/assets/8516358/3e55e981-3b2c-4136-9f82-5ed3ae4bdd57)

The build error I do get is

![image](https://github.com/darkrenaissance/darkfi/assets/8516358/54edfccd-0383-47b8-b0af-b84addf309a6)

Looks like the [alsa development headers](https://github.com/diwic/alsa-sys/blob/3a6d3b26bdc21ac74a0ba6e4a637decf20da0a39/build.rs#L9-L13) are needed.  On my system I had to install `libasound2-dev`.

`make check` works now :tada:

**Comment by parazyd** [comment]
Ok yeah, thanks. Will test it on a clean system and report back.

**Comment by aggstam** [comment]
@adoerr: `libasound2-dev` was added as dependency in docs, scripts, etc.
Let us know if you encounter any issue with `fun` feature, otherwise we can close this ticket.
Your feedback is really appreciated!

On a sidenote, please prefer using `codeblocks` rather than `screenshots` to share logs.

**Comment by adoerr** [comment]
Fixed.
