### ISSUE TITLE
Unable to connect to darkirc

### ISSUE THREAD

**Issue by ggreptile** [darkrenaissance/darkfi#187]
## Issue

I was connected to darkirc chat before but now I'm unable to join. It appears that I'm unable to connect to the seeds (via lilith).

Commit hash: `d2449259bca75ac160973050177d44336e0e2bd5` (origin/master)

## Troubleshooting steps attempted
- Rebuilding (`make clean; make; make install`)
- Checking out an older version of the repo in order to build `ircd` (instead of `darkirc`) and connect as I had previously
- Changing the port for lilith from default 26661 to 25551 (as per https://github.com/darkrenaissance/darkfi/blob/d2449259bca75ac160973050177d44336e0e2bd5/bin/lilith/lilith_config.toml#L39-L40)
- Changing protocol to `tls` instead of `tcp+tls`

### Port 26661
```
$ ./darkirc # from root of repository
21:04:00 [INFO] [P2P] Seeding P2P subsystem
21:04:00 [WARN] [P2P] Failure contacting seed #0 [tcp+tls://lilith0.dark.fi:26661]: IO error: connection refused
21:04:00 [WARN] [P2P] Seed #0 connection failed: IO error: connection refused
21:04:00 [WARN] [P2P] Failure contacting seed #1 [tcp+tls://lilith1.dark.fi:26661]: IO error: connection refused
21:04:00 [WARN] [P2P] Seed #1 connection failed: IO error: connection refused
21:04:00 [WARN] [P2P] Hosts pool empty after seeding
21:04:00 [INFO] [P2P] Running P2P subsystem
21:04:00 [INFO] [P2P] Not configured for inbound connections.
21:04:00 [INFO] [P2P] Starting 8 outbound connection slots.
21:04:00 [INFO] [IRC SERVER] listening on tcp://127.0.0.1:6667
21:04:00 [INFO] [P2P] Outbound #0: No peers found. Starting peer discovery...
21:04:00 [INFO] reset current root to: Hash("37baf943bc8eb168bba77075cc4726977949d5188e90139bbe7c7fc21105cab5")
21:04:00 [INFO] [P2P] Outbound #1: No peers found. Starting peer discovery...
21:04:00 [INFO] [P2P] Outbound #1: Started peer discovery
21:04:00 [INFO] [P2P] Outbound #7: No peers found. Starting peer discovery...
21:04:00 [INFO] [P2P] Outbound #7: Peer discovery already active
21:04:00 [INFO] [P2P] P2P subsystem started
21:04:00 [INFO] [P2P] Outbound #3: No peers found. Starting peer discovery...
21:04:00 [INFO] [P2P] Outbound #3: Peer discovery already active
21:04:00 [INFO] [P2P] Outbound #1: Broadcasting GetAddrs across active channels
21:04:00 [WARN] P2P: No connected channels found for broadcast
21:04:00 [INFO] [P2P] Outbound #4: No peers found. Starting peer discovery...
21:04:00 [INFO] [P2P] Outbound #4: Peer discovery already active
21:04:00 [INFO] [P2P] Outbound #0: Started peer discovery
21:04:00 [INFO] [P2P] Outbound #0: Broadcasting GetAddrs across active channels
21:04:00 [WARN] P2P: No connected channels found for broadcast
21:04:03 [INFO] Caught termination signal, cleaning up and exiting...
21:04:03 [INFO] [P2P] Received P2P subsystem stop signal. Shutting down.
```

### Port 25551
```
21:03:24 [INFO] [P2P] Seeding P2P subsystem
21:03:24 [ERROR] [net::tls] Failed verifying server certificate signature: invalid peer certificate: BadEncoding
21:03:24 [WARN] [P2P] Failure contacting seed #0 [tcp+tls://lilith0.dark.fi:25551]: IO error: invalid data
21:03:24 [WARN] [P2P] Seed #0 connection failed: IO error: invalid data
21:03:24 [ERROR] [net::tls] Failed verifying server certificate signature: invalid peer certificate: BadEncoding
21:03:24 [WARN] [P2P] Failure contacting seed #1 [tcp+tls://lilith1.dark.fi:25551]: IO error: invalid data
21:03:24 [WARN] [P2P] Seed #1 connection failed: IO error: invalid data
21:03:24 [WARN] [P2P] Hosts pool empty after seeding
21:03:24 [INFO] [P2P] Running P2P subsystem
21:03:24 [INFO] [P2P] Not configured for inbound connections.
21:03:24 [INFO] [P2P] Starting 8 outbound connection slots.
21:03:24 [INFO] [IRC SERVER] listening on tcp://127.0.0.1:6667
21:03:24 [INFO] reset current root to: Hash("37baf943bc8eb168bba77075cc4726977949d5188e90139bbe7c7fc21105cab5")
21:03:24 [INFO] [P2P] Outbound #2: No peers found. Starting peer discovery...
21:03:24 [INFO] [P2P] Outbound #2: Started peer discovery
21:03:24 [INFO] [P2P] Outbound #1: No peers found. Starting peer discovery...
21:03:24 [INFO] [P2P] Outbound #1: Peer discovery already active
21:03:24 [INFO] [P2P] Outbound #0: No peers found. Starting peer discovery...
21:03:24 [INFO] [P2P] Outbound #0: Peer discovery already active
21:03:24 [INFO] [P2P] P2P subsystem started
21:03:24 [INFO] [P2P] Outbound #2: Broadcasting GetAddrs across active channels
21:03:24 [WARN] P2P: No connected channels found for broadcast
21:03:26 [INFO] Caught termination signal, cleaning up and exiting...
21:03:26 [INFO] [P2P] Received P2P subsystem stop signal. Shutting down.
```

**Comment by parazyd** [comment]
Try using `tcp+tls://alpinewg.parazyd.org:5262` as the seed node in your config file instead.

**Comment by ggreptile** [comment]
14:06:46 [INFO] [P2P] Outbound #2: No peers found. Starting peer discovery...
14:06:46 [INFO] [P2P] Outbound #2: Peer discovery already active
14:06:46 [INFO] [P2P] Outbound #7: No peers found. Starting peer discovery...
14:06:46 [INFO] [P2P] Outbound #7: Peer discovery already active
14:06:46 [INFO] [P2P] Outbound slot #0 connected [tcp+tls://dasman.xyz:26661]
14:06:46 [INFO] [P2P] Outbound slot #5 connected [tcp+tls://alpinewg.parazyd.org:26661]
14:06:46 [INFO] [P2P] Outbound slot #3 connected [tcp+tls://acab.accesscam.org:26661]
14:06:46 [INFO] Found configuration for channel #dev
14:06:46 [INFO] Found topic for channel #dev: DarkFi Development HQ
14:06:46 [INFO] Found configuration for channel #markets
14:06:46 [INFO] Found topic for channel #markets: Crypto Market Talk
14:06:46 [INFO] Found configuration for channel #math
14:06:46 [INFO] Found topic for channel #math: Math Talk
14:06:46 [INFO] Found configuration for channel #memes
14:06:46 [INFO] Found topic for channel #memes: DarkFi Meme Reality
14:06:46 [INFO] Found configuration for channel #philosophy
14:06:46 [INFO] Found topic for channel #philosophy: Philosophy Discussions
14:06:46 [INFO] Found configuration for channel #random
14:06:46 [INFO] Found topic for channel #random: /b/
14:06:46 [INFO] Found secret key in config, noted it down.
14:06:46 [INFO] [IRC SERVER] Accept new connection: 127.0.0.1:44936
14:07:01 [INFO] [P2P] Connecting outbound slot #1 [tcp+tls://250.251.forpsi.net:26661]
14:07:01 [INFO] [P2P] Outbound #2: No peers found. Starting peer discovery...
14:07:01 [INFO] [P2P] Outbound #2: Started peer discovery
14:07:01 [INFO] [P2P] Outbound #2: Broadcasting GetAddrs across active channels
14:07:01 [INFO] [P2P] Outbound #4: No peers found. Starting peer discovery...
14:07:01 [INFO] [P2P] Outbound #4: Started peer discovery
14:07:01 [INFO] [P2P] Outbound #4: Broadcasting GetAddrs across active channels
14:07:01 [INFO] [P2P] Outbound #6: No peers found. Starting peer discovery...
14:07:01 [INFO] [P2P] Outbound #6: Peer discovery already active
14:07:01 [INFO] [P2P] Outbound #7: No peers found. Starting peer discovery...
14:07:01 [INFO] [P2P] Outbound #7: Peer discovery already active
14:07:01 [ERROR] [P2P] Unable to connect outbound slot #1 [tcp+tls://250.251.forpsi.net:26661]: IO error: connection refused
14:07:01 [ERROR] [P2P] Outbound slot #1 connection failed: Connection failed
14:07:16 [INFO] [P2P] Outbound #2: No peers found. Starting peer discovery...
14:07:16 [INFO] [P2P] Outbound #7: No peers found. Starting peer discovery...
14:07:16 [INFO] [P2P] Outbound #7: Started peer discovery
14:07:16 [INFO] [P2P] Outbound #7: Broadcasting GetAddrs across active channels
14:07:16 [INFO] [P2P] Outbound #2: Started peer discovery
14:07:16 [INFO] [P2P] Outbound #2: Broadcasting GetAddrs across active channels
14:07:16 [INFO] [P2P] Outbound #6: No peers found. Starting peer discovery...
14:07:16 [INFO] [P2P] Outbound #6: Peer discovery already active
14:07:16 [INFO] [P2P] Outbound #1: No peers found. Starting peer discovery...
14:07:16 [INFO] [P2P] Outbound #1: Peer discovery already active
```
