### ISSUE TITLE
mismatched types

### ISSUE THREAD

**Issue by 0xvenom** [darkrenaissance/darkfi#19]
error[E0308]: mismatched types
   --> src/client.rs:107:81
    |
107 |             let input = tx::TransactionBuilderClearInputInfo { value, token_id, signature_secret };
    |                                                                                 ^^^^^^^^^^^^^^^^ expected struct `crypto::schnorr::SecretKey`, found struct `pasta_curves::Fp`

error[E0609]: no field `witness` on type `&OwnCoin`
   --> src/client.rs:121:41
    |
121 |                 let witness = &own_coin.witness;
    |                                         ^^^^^^^ unknown field
    |
    = note: available fields are: `coin`, `note`, `secret`, `nullifier`

error[E0063]: missing field `leaf_position` in initializer of `TransactionBuilderInputInfo`
   --> src/client.rs:125:29
    |
125 |                 let input = tx::TransactionBuilderInputInfo {
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `leaf_position`

error[E0308]: mismatched types
   --> src/client.rs:245:35
    |
245 |         self.public_keys.contains(public)
    |                                   ^^^^^^ expected struct `Ep`, found struct `crypto::schnorr::PublicKey`
    |
    = note: expected reference `&Ep`
               found reference `&crypto::schnorr::PublicKey`

Some errors have detailed explanations: E0063, E0308, E0609.
For more information about an error, try `rustc --explain E0063`.
error: could not compile `darkfi` due to 4 previous errors
make: *** [Makefile:21: all] Error 101

**Comment by 0xvenom** [comment]
@parazyd @gazhayes @mattsse @lunar-mining

**Comment by 0xvenom** [comment]
sorry for closing lmao. fat finger

**Comment by parazyd** [comment]
The current git HEAD is not yet ready for consumption. Checkout the `v0.0.1` tag and compile that.

**Comment by monomadic** [comment]
@parazyd might I suggest using a gitflow approach, as most people are pulling master.

Have a primary `master` branch that always compiles (use CI/CD), a `development` or `staging` branch that carries potentially unstable code (but still passing CI/CD) and then branches for hotfixes, features etc.

I'm not a big fan of process, but having errors in master is completely avoidable, and could deter new coders from assisting on your project - I was actually seeing if I wanted to contrib myself :)

**Comment by parazyd** [comment]
That makes sense, but this has been a major change and we're still not at a point where we have to worry too much, so it's better to have a single branch right now to avoid too much diverging work (as has happened).

However, this should not be stopping you from contributing to be honest.

**Comment by parazyd** [comment]
You can compile the project now.
