### ISSUE TITLE
Wrong cashier PublicKey ? 

### ISSUE THREAD

**Issue by securixhk** [darkrenaissance/darkfi#21]
Hello,

When launching the daemon (_darkfid -v_), I get : 

**DEBUG [drk::crypto::keypair] Failed decoding PublicKey
Error: BadOperationType**

Is the publickey included in darkfid.toml anymore used ? 

Thanks

**Comment by Dastan-glitch** [comment]
`git checkout v0.0.1`
Please read the [README](https://github.com/darkrenaissance/darkfi#note-use-the-v001-git-tag-if-you-want-to-try-out-the-software)
