### ISSUE TITLE
Connection fails when switching from versioned ircd to darkirc

### ISSUE THREAD

**Issue by bobsummerwill** [darkrenaissance/darkfi#212]
I has just switched from using the previous versioned release to using the head of master, and am attempting to switch over to darkirc, but it never connects.   weechat never connects successfully.

Initial log for darkirc:

22:34:40 [0m[34m[INFO] [0mTree is loaded from disk
22:34:40 [0m[34m[INFO] [0mTree is loaded from disk
22:34:40 [0m[34m[INFO] [0mStarting dnet subs task
22:34:40 [0m[34m[INFO] [0mStarting JSON-RPC server on tcp://127.0.0.1:26660
22:34:40 [0m[34m[INFO] [0mStarting P2P network
22:34:40 [0m[34m[INFO] [0m[P2P] Starting P2P subsystem
22:34:40 [0m[34m[INFO] [0m[P2P] Not configured for inbound connections.
22:34:40 [0m[34m[INFO] [0m[P2P] Starting 8 outbound connection slots.
22:34:40 [0m[34m[INFO] [0m[P2P] P2P subsystem started
22:34:40 [0m[34m[INFO] [0m[P2P] Seeding hosts. Attempt: 1
22:34:40 [0m[34m[INFO] [0m[P2P] Seeding P2P subsystem
22:34:40 [0m[34m[INFO] [0mStarting IRC server
22:34:40 [0m[34m[INFO] [0mStarting remove old events task
22:34:40 [0m[31m[ERROR] [0mFailed starting IRC server: IO error: address in use
22:34:40 [0m[31m[ERROR] [0mFailed starting listen to msgs: async_channel receiver error: receiving from an empty and closed channel
22:34:40 [0m[34m[INFO] [0mRemoving old events
22:34:40 [0m[34m[INFO] [0m[P2P] Connected seed #0 [tcp+tls://lilith0.dark.fi:5262]
22:34:41 [0m[34m[INFO] [0m[P2P] Connected seed #1 [tcp+tls://lilith1.dark.fi:5262]
22:34:41 [0m[34m[INFO] [0m[P2P] Disconnecting from seed #0 [tcp+tls://lilith0.dark.fi:5262]
22:34:41 [0m[34m[INFO] [0m[P2P] Disconnecting from seed #1 [tcp+tls://lilith1.dark.fi:5262]
22:34:41 [0m[34m[INFO] [0m[P2P] Seeding hosts successful.
22:34:41 [0m[34m[INFO] [0m[P2P] Connecting outbound slot #0 [tcp+tls://agorism.dev:26661]
22:34:41 [0m[34m[INFO] [0m[P2P] Connecting outbound slot #5 [tcp+tls://acab.accesscam.org:26661]
22:34:41 [0m[34m[INFO] [0m[P2P] Connecting outbound slot #7 [tcp+tls://[2a02:aa13:8342:1400:8038:3322:c0f8:295e]:26661]
22:34:41 [0m[34m[INFO] [0m[P2P] Connecting outbound slot #6 [tcp+tls://dasman.xyz:26661]
22:34:41 [0m[34m[INFO] [0m[P2P] Connecting outbound slot #1 [tcp+tls://alpinewg.parazyd.org:26661]
22:34:41 [0m[31m[ERROR] [0m[P2P] Unable to connect outbound slot #0 [tcp+tls://agorism.dev:26661]: IO error: connection refused
22:34:41 [0m[31m[ERROR] [0m[P2P] Outbound slot #0 connection failed: Connection failed
22:34:42 [0m[31m[ERROR] [0m[P2P] Unable to connect outbound slot #7 [tcp+tls://[2a02:aa13:8342:1400:8038:3322:c0f8:295e]:26661]: IO error: connection refused
22:34:42 [0m[31m[ERROR] [0m[P2P] Outbound slot #7 connection failed: Connection failed
22:34:42 [0m[31m[ERROR] [0m[P2P] Unable to connect outbound slot #1 [tcp+tls://alpinewg.parazyd.org:26661]: IO error: connection refused
22:34:42 [0m[31m[ERROR] [0m[P2P] Outbound slot #1 connection failed: Connection failed

And then it goes into a perpetual loop of ...

22:34:46 [0m[34m[INFO] [0m[P2P] Seeding hosts. Attempt: 2
22:34:46 [0m[34m[INFO] [0m[P2P] Seeding P2P subsystem
22:34:46 [0m[34m[INFO] [0m[P2P] Connected seed #0 [tcp+tls://lilith0.dark.fi:5262]
22:34:46 [0m[34m[INFO] [0m[P2P] Connected seed #1 [tcp+tls://lilith1.dark.fi:5262]
22:34:47 [0m[34m[INFO] [0m[P2P] Disconnecting from seed #0 [tcp+tls://lilith0.dark.fi:5262]
22:34:47 [0m[34m[INFO] [0m[P2P] Disconnecting from seed #1 [tcp+tls://lilith1.dark.fi:5262]
22:34:47 [0m[34m[INFO] [0m[P2P] Seeding hosts successful.
22:34:47 [0m[34m[INFO] [0m[P2P] Connecting outbound slot #0 [tcp+tls://[2a02:aa13:8342:1400:8038:3322:c0f8:295e]:26661]
22:34:47 [0m[34m[INFO] [0m[P2P] Connecting outbound slot #7 [tcp+tls://alpinewg.parazyd.org:26661]
22:34:47 [0m[34m[INFO] [0m[P2P] Connecting outbound slot #1 [tcp+tls://agorism.dev:26661]
22:34:47 [0m[31m[ERROR] [0m[P2P] Unable to connect outbound slot #1 [tcp+tls://agorism.dev:26661]: IO error: connection refused
22:34:47 [0m[31m[ERROR] [0m[P2P] Outbound slot #1 connection failed: Connection failed
22:34:48 [0m[31m[ERROR] [0m[P2P] Unable to connect outbound slot #0 [tcp+tls://[2a02:aa13:8342:1400:8038:3322:c0f8:295e]:26661]: IO error: connection refused
22:34:48 [0m[31m[ERROR] [0m[P2P] Outbound slot #0 connection failed: Connection failed
22:34:48 [0m[31m[ERROR] [0m[P2P] Unable to connect outbound slot #7 [tcp+tls://alpinewg.parazyd.org:26661]: IO error: connection refused
22:34:48 [0m[31m[ERROR] [0m[P2P] Outbound slot #7 connection failed: Connection failed

I assume this is some issue with those seeded outbound connections and they are essential?

[2a02:aa13:8342:1400:8038:3322:c0f8:295e]:26661
alpinewg.parazyd.org:26661
agorism.dev:26661

This is using default everything.

**Comment by ggreptile** [comment]
@bobsummerwill it looks like you're using an outdated configuration file. 

The seed nodes should look like the following:
https://github.com/darkrenaissance/darkfi/blob/5ac3af091cad9ebec284634113485d29ee8169b9/bin/darkirc/darkirc_config.toml#L49-L52

Could you replace the seed nodes you have configured and try to connect again?

**Comment by bobsummerwill** [comment]
Aborted this effort and back to ircd on a new machine:
https://github.com/darkrenaissance/darkfi/issues/225
