### ISSUE TITLE
BridgeError on Solana network ?

### ISSUE THREAD

**Issue by securixhk** [darkrenaissance/darkfi#22]
Hey everyone,

Can't get Solana deposit address (while it works for BTC and ETH) : 

_root@ubuntu:# drk features
Features: {"hosts":{"dns_addr":"testnet.cashier.dark.fi","onion_addr":null,"tcp_port":9000,"tls_port":null},"networks":[{"solana":{"chain":"devnet"}},{"bitcoin":{"chain":"testnet"}},{"ethereum":{"chain":"ropsten"}}],"protocol_version":"1.0","public_key":"95MPgrASV5WQ6DgoVaWgamrnCFN3V5FZrJNCUWWhDEKz","server_version":"0.1.0"}
root@ubuntu:# drk deposit btc --network bitcoin
Deposit your coins to the following address: "n3mvd***********"
root@ubuntu:# drk deposit eth --network ethereum
Deposit your coins to the following address: "0xed**********"
**root@ubuntu:# drk deposit sol --network solana
Error: JsonRpcError("\"BridgeError Error: `Unable to watch the deposit address`\"")**
root@ubuntu:#_

Error on darkfi daemon : 
**_2021-12-10 10:16:51,974 DEBUG [RPC] <-- {"jsonrpc":"2.0","error":{"code":-32603,"message":"BridgeError Error: `Unable to watch the deposit address`"},"id":2698246173}_**

**Any idea 🤔 ?** 

Thanks 😄 !

**Comment by parazyd** [comment]
Solana should work fine now with the latest `v0.2.0` tag. Please recompile your repository or clone anew.

**Comment by securixhk** [comment]
Great @parazyd 🙌 ! Thanks a lot, will try it :) .
