### ISSUE TITLE
Cannot connect on returning to ircd

### ISSUE THREAD

**Issue by bobsummerwill** [darkrenaissance/darkfi#225]
Brand new machine, running Ubuntu 23.04, with v0.4.1 ircd with default config, weechat.

test, test back on random is not working and not getting any replies.   Is there a good way to debug here?

01:26:37 [0m[34m[INFO] [0mnet::seedsync_session: Connected seed #0 [tls://lilith0.dark.fi:25551]
01:26:37 [0m[34m[INFO] [0mnet::seedsync_session: Connected seed #1 [tls://lilith1.dark.fi:25551]
01:26:37 [0m[34m[INFO] [0mnet::seedsync_session: Disconnecting from seed #0 [tls://lilith0.dark.fi:25551]
01:26:37 [0m[34m[INFO] [0mnet::seedsync_session: Seed #0 connected successfully
01:26:38 [0m[34m[INFO] [0mnet::seedsync_session: Disconnecting from seed #1 [tls://lilith1.dark.fi:25551]
01:26:38 [0m[34m[INFO] [0mnet::seedsync_session: Seed #1 connected successfully
01:26:38 [0m[34m[INFO] [0mnet::inbound_session: Not configured for accepting incoming connections.
01:26:38 [0m[34m[INFO] [0mnet::outbound_session: Starting 5 outbound connection slots.
01:26:38 [0m[34m[INFO] [0mircd::settings: Found configuration for channel #dev
01:26:38 [0m[34m[INFO] [0mircd::settings: Found topic for channel #dev: DarkFi Development HQ
01:26:38 [0m[34m[INFO] [0mnet::outbound_session: #0 processing outbound [tor://pwxv55txflxhbtky2tm5sdwjqsbxckvtgpyx6o3zokz4to7ufabct3ad.onion:25551]
01:26:38 [0m[34m[INFO] [0mrpc::server: JSON-RPC listener bound to tcp://127.0.0.1:25550
01:26:38 [0m[33m[WARN] [0mnet::outbound_session: #0 address tor://pwxv55txflxhbtky2tm5sdwjqsbxckvtgpyx6o3zokz4to7ufabct3ad.onion:25551 transport is not in accepted outbound transports, will try with: [Tcp(Some("tls"))]
01:26:38 [0m[34m[INFO] [0mircd::irc: [IRC SERVER] listening on tcp://127.0.0.1:6667
01:26:38 [0m[34m[INFO] [0mnet::outbound_session: #1 processing outbound [tls://chara.htznr.fault.dev:25778]
01:26:38 [0m[34m[INFO] [0mnet::outbound_session: #3 processing outbound [tls://alpinewg.parazyd.org:25551]
01:26:38 [0m[34m[INFO] [0mnet::outbound_session: #4 processing outbound [tls://irc0.dark.fi:11001]
01:26:38 [0m[34m[INFO] [0mnet::outbound_session: #1 connecting to outbound [tcp+tls://chara.htznr.fault.dev:25778]
01:26:38 [0m[34m[INFO] [0mnet::outbound_session: #0 connecting to outbound [tcp+tls://pwxv55txflxhbtky2tm5sdwjqsbxckvtgpyx6o3zokz4to7ufabct3ad.onion:25551]
01:26:38 [0m[34m[INFO] [0mnet::outbound_session: #3 connecting to outbound [tcp+tls://alpinewg.parazyd.org:25551]
01:26:38 [0m[34m[INFO] [0mnet::outbound_session: #4 connecting to outbound [tcp+tls://irc0.dark.fi:11001]
01:26:38 [0m[31m[ERROR] [0mnet::connector: Setup for tcp+tls://pwxv55txflxhbtky2tm5sdwjqsbxckvtgpyx6o3zokz4to7ufabct3ad.onion:25551 failed: IO error: uncategorized error
01:26:38 [0m[31m[ERROR] [0mnet::outbound_session: Unable to connect to outbound [tcp+tls://pwxv55txflxhbtky2tm5sdwjqsbxckvtgpyx6o3zokz4to7ufabct3ad.onion:25551]: Connection failed
01:26:38 [0m[31m[ERROR] [0mnet::outbound_session: #0 slot connection failed: Connection failed
01:26:38 [0m[34m[INFO] [0mnet::outbound_session: #2 processing outbound [tls://acab.accesscam.org:25561]
01:26:38 [0m[34m[INFO] [0mnet::outbound_session: #2 connecting to outbound [tcp+tls://acab.accesscam.org:25561]
01:26:38 [0m[31m[ERROR] [0mnet::connector: Connection to tcp+tls://alpinewg.parazyd.org:25551  failed: IO error: connection refused
01:26:38 [0m[31m[ERROR] [0mnet::outbound_session: Unable to connect to outbound [tcp+tls://alpinewg.parazyd.org:25551]: Connection failed
01:26:38 [0m[31m[ERROR] [0mnet::outbound_session: #3 slot connection failed: Connection failed
01:26:38 [0m[34m[INFO] [0mnet::outbound_session: #4 connected to outbound [tcp+tls://irc0.dark.fi:11001]
01:26:38 [0m[34m[INFO] [0mnet::outbound_session: #1 connected to outbound [tcp+tls://chara.htznr.fault.dev:25778]
01:26:38 [0m[34m[INFO] [0mnet::outbound_session: #2 connected to outbound [tcp+tls://acab.accesscam.org:25561]
01:27:48 [0m[34m[INFO] [0mircd::irc: [IRC SERVER] Accept new connection: 127.0.0.1:38428
01:27:48 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:38428] Msg: CAP LS 302
01:27:48 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:38428] Msg: NICK bob
01:27:48 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:38428] Msg: USER bob 0 * :bob
01:27:48 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:38428] Msg: CAP END
01:27:48 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:38428] Msg: JOIN #dev,#memes,#philosophy,#markets,#math,#random
01:28:48 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:38428] Msg: PING localhost
01:29:11 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:38428] Msg: PRIVMSG #random :test
01:29:11 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:38428] (Plain) PRIVMSG #random :test
01:29:11 [0m[34m[INFO] [0mircd::irc::client: [P2P] Broadcast: Privmsg { id: 605593098237323717, nickname: "bob", target: "#random", message: "test", timestamp: 1695000551, term: 0, read_confirms: 0 }
01:29:29 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:38428] Msg: PRIVMSG #dev :test
01:29:29 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:38428] (Plain) PRIVMSG #dev :test
01:29:29 [0m[34m[INFO] [0mircd::irc::client: [P2P] Broadcast: Privmsg { id: 11968809244502595463, nickname: "bob", target: "#dev", message: "test", timestamp: 1695000569, term: 0, read_confirms: 0 }
01:29:48 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:38428] Msg: PING localhost
01:30:48 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:38428] Msg: PING localhost
01:31:48 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:38428] Msg: PING localhost
01:32:48 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:38428] Msg: PING localhost
01:33:48 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:38428] Msg: PING localhost
01:34:48 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:38428] Msg: PING localhost
01:35:48 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:38428] Msg: PING localhost
01:36:48 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:38428] Msg: PING localhost
01:37:48 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:38428] Msg: PING localhost
01:38:48 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:38428] Msg: PING localhost
01:39:44 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:38428] Msg: QUIT :WeeChat 3.8
01:39:44 [0m[33m[WARN] [0mircd::irc::client: [CLIENT 127.0.0.1:38428] Connection error: Network service stopped
01:39:44 [0m[31m[ERROR] [0mircd::irc::client: [CLIENT 127.0.0.1:38428] Process line failed: Channel stopped
01:39:44 [0m[33m[WARN] [0mircd::irc::client: [CLIENT 127.0.0.1:38428] Close connection
01:39:52 [0m[34m[INFO] [0mircd::irc: [IRC SERVER] Accept new connection: 127.0.0.1:53270
01:39:52 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:53270] Msg: CAP LS 302
01:39:52 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:53270] Msg: NICK bob
01:39:52 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:53270] Msg: USER bob 0 * :bob
01:39:52 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:53270] Msg: CAP END
01:39:58 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:53270] Msg: PRIVMSG #random :test
01:39:58 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:53270] (Plain) PRIVMSG #random :test
01:39:58 [0m[34m[INFO] [0mircd::irc::client: [P2P] Broadcast: Privmsg { id: 11478870519782067562, nickname: "bob", target: "#random", message: "test", timestamp: 1695001198, term: 0, read_confirms: 0 }
01:40:02 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:53270] Msg: QUIT :WeeChat 3.8
01:40:02 [0m[33m[WARN] [0mircd::irc::client: [CLIENT 127.0.0.1:53270] Connection error: Network service stopped
01:40:02 [0m[31m[ERROR] [0mircd::irc::client: [CLIENT 127.0.0.1:53270] Process line failed: Channel stopped
01:40:02 [0m[33m[WARN] [0mircd::irc::client: [CLIENT 127.0.0.1:53270] Close connection
01:43:02 [0m[34m[INFO] [0mircd::irc: [IRC SERVER] Accept new connection: 127.0.0.1:54050
01:43:02 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:54050] Msg: CAP LS 302
01:43:02 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:54050] Msg: NICK bob
01:43:02 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:54050] Msg: USER bob 0 * :bob
01:43:02 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:54050] Msg: CAP END
01:43:09 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:54050] Msg: PRIVMSG #dev :test
01:43:09 [0m[34m[INFO] [0mircd::irc::client: [CLIENT 127.0.0.1:54050] (Plain) PRIVMSG #dev :test
01:43:09 [0m[34m[INFO] [0mircd::irc::client: [P2P] Broadcast: Privmsg { id: 7422299996001144666, nickname: "bob", target: "#dev", message: "test", timestamp: 1695001389, term: 0, read_confirms: 0 }

**Comment by ggreptile** [comment]
Hey bob I think you happened to login when no one was online. I saw your `test` messages when I logged in later. The 'test back' bot was also down and is now back. Could you try again?

**Comment by bobsummerwill** [comment]
OK - test back bot replied, so I guess I am connected again.  Thanks!
