### ISSUE TITLE
Installation Instructions Missing `libclang-dev`

### ISSUE THREAD

**Issue by bonedaddy** [darkrenaissance/darkfi#236]
# Overview

The installation instructions are missing the `libclang-dev` dependency from the list of dependencies which need to be installed.

**Comment by aggstam** [comment]
Hello @bonedaddy ,

Can you please specify your os/distro?
This package should come as a dep to gcc which is in the dependencies table and [dependency_setup](https://github.com/darkrenaissance/darkfi/blob/master/contrib/dependency_setup.sh) script.

**Comment by bonedaddy** [comment]
os

```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
```


kernel

```
Linux pop-os 6.5.6-76060506-generic #202310061235~1697396945~22.04~9283e32 SMP PREEMPT_DYNAMIC Sun O x86_64 x86_64 x86_64 GNU/Linux
```

I installed the dependencies manually so that might be why

**Comment by aggstam** [comment]
Manually installation was not the root issue.
`PoP!_OS` seems to have split `libclang-dev` and not ship it as default, hence why it was "missing" from your OS.
This is a derivative distro modification, therefore this is not the case for upstream `debian` (or normal derivatives).
I don't see a need to add it as a dependency, or add it in the dependencies setup script, as those assume upstream `apt` using distros, therefore closing this ticket.
Happy to provide any further assistance!

**Comment by bonedaddy** [comment]
Ah makes sense thanks for the clarification. Yea I wouldn't bother adding it to the dependencies setup script since i doubt a lot of people will be using PoP!_OS.
