### ISSUE TITLE
`darkifd` Doesn't Respond To CTRL+C 

### ISSUE THREAD

**Issue by bonedaddy** [darkrenaissance/darkfi#237]
As of version `0.4.1` I'm unable to terminate the `darkfid` process from the terminal it is executing it. Hitting `CTRL+C` doesn't seem to result in the process terminating, requiring one to run `kill -9 <PID>`.

Not sure if this is intended behavior but figured I would report the issue just in case.

**Comment by aggstam** [comment]
Hello @bonedaddy ,

I asume you refer to `tag v0.4.1`, and not binary version 0.4.1.
This termination is due to a loop deadlock during sync, already fixed on latest branches.
Keep in mind that refered tag version is old and will be replaced with later releases.

**Comment by aggstam** [comment]
You should join `ircd`, would make it much easier/faster to communicate already known stuff.
