### ISSUE TITLE
Improve nixos flake installation

### ISSUE THREAD

**Issue by pipelight** [darkrenaissance/darkfi#241]
The actual nix flake is great, but it can not be used as is.

After cloning the repo, one either have to: 
- 1, move the flake.nix file to project root, 
- 2, or to change the relative paths inside the flake.nix

If you want to keep the root clean,
I suggest we change relative paths so the flake can be installed with

```nix
 darkfi.url = "github:darkrenaissance/darkfi?dir=contrib";
```

and no further manipulations.

Or just move flake.nix to the project root
   
I can pull btw

**Comment by aggstam** [comment]
Hey @pipelight !

Contrib folder contains stuff that are not related to source code, like distros deps setup, docker images, etc. etc., so yeah we want to keep them out of repo root.

I'm not a nix user, so I can't really comment on the flake quality, but I see some apps are outdated compared to current master. So feel free to create a PR using the proposed relative path, and updating rest contents. It would also be nice if you could verify the whole file integrity, by checking everything works as it should.

KR

**Comment by pipelight** [comment]
I'll double check everything!! Thanks for you promptitude!

**Comment by pipelight** [comment]
I just put those stuff in a separate repo
https://github.com/pipelight/darkfi.nix
