### ISSUE TITLE
Sollet BTC/BTC has same interface on drk

### ISSUE THREAD

**Issue by lunar-mining** [darkrenaissance/darkfi#26]

**Comment by parazyd** [comment]
Was this solved by having the BTC token list?
https://github.com/darkrenaissance/darkfi/tree/master/contrib/token

As seen here: https://github.com/darkrenaissance/darkfi/blob/master/contrib/token/Makefile#L17
We change the Solana aliases/tickers to SBTC and SETH.

**Comment by lunar-mining** [comment]
Correct, it seems like this was solved. Closing this issue.
