### ISSUE TITLE
DarkIRC: USER command not supported, error connecting

### ISSUE THREAD

**Issue by jaromil** [darkrenaissance/darkfi#274]
As seen in darkirc logs:
![image](https://github.com/user-attachments/assets/d9d2a5ef-2649-440c-b4ab-c006d0f1c6a3)
when connecting some IRC clients send a USER command, even when not configured to use authentication.

DarkIRC errors out and aborts connection, but I think it should tolerate this and move forward connecting the client, no?

**Comment by aggstam** [comment]
Issue fixed in commit 880e2a9c4d6dece853f85806bdd5d255acdcb64b
