### ISSUE TITLE
Unable to connect to seed

### ISSUE THREAD

**Issue by skynetcap** [darkrenaissance/darkfi#276]
02:38:48 [INFO] [P2P] [PEER DISCOVERY] Asking seeds for new peers to connect to...
02:38:48 [WARN] [P2P] Unable to connect to seed [tcp+tls://lilith0.dark.fi:8342/]: IO error: uncategorized error
02:38:48 [WARN] [P2P] Unable to connect to seed [tcp+tls://lilith1.dark.fi:8342/]: IO error: uncategorized error
02:38:53 [INFO] Caught termination signal, cleaning up and exiting...

- Opened port 8342, still broken.

**Comment by aggstam** [comment]
There was an issue with the seed that day, should be fine now.
Reopen if issue persists.
