### ISSUE TITLE
No rule to make target 'install'

### ISSUE THREAD

**Issue by skynetcap** [darkrenaissance/darkfi#288]
After cloning main and following steps on a fresh Ubuntu.
```
cd darkfi
make install
make: *** No rule to make target 'install'.  Stop.
```

Maybe I did something wrong, or there's something small missing in the Makefile. Thought I'd report it.

**Comment by aggstam** [comment]
`install` target has been removed since its not needed in this phase of the project. Invoke everything from repo root folder.
