### ISSUE TITLE
Separate `src` into specific namespaces, and move modules to features

### ISSUE THREAD

**Issue by parazyd** [darkrenaissance/darkfi#35]
* `blockchain/`
* `crypto/`
* `net/`
* `tx/`
* `wallet/`
* `system/`
* `zk/`
* `util/`

Software in `bin/` should go in individual sub-crates with own modules and stuff.

**Comment by narodnik** [comment]
Also the old architecture.md document had this hierarchy:

* **system/** contains core functionality, types and utilities.
* **net/** is the p2p networking base layer.
* **zk/** is the zk lisp virtual machine and related zk code.
* **crypto/** for the transaction builder and merkle tree classes.
* **node/** is a fully working darkfi node.
* **wallet/** key generation and management features such as derivation and storage.
* **service/** any services such as the cashier or gateways.
* **chain/** blockchain database functionality and state transition.
* **rpc/** interface for remote procedure calls, includes adapter to interface with the node backend and the default jsonrpc transport mechanism.

**Comment by narodnik** [comment]
We should keep `rpc/` in the main library somewhere since it is very useful to be able to add a jsonrpc server to an app. Maybe under `util/rpc/`?

`service` can maybe go in `node/service/`.

**Comment by ghassmo** [comment]
i finished this part:
- moved wallet, client, service and state modules to node directory and made it a feature
- made blockchain directory work as a feature
- create zk directory and moved vm module to that
- moved serial and error modules to util directory 
- moved darkfid, gatewayd, and drk binaries to sub-crates in bin/ directory
- moved cashierd and all the bridges to bin/cashier sub-crate

**Comment by lunar-mining** [comment]
as of commit #d001a140dc9ce4c26eaaa02f8e747da2b21c00c2 this is the current directory hierarchy:

```
/src
    /chain
    /cli
    /crypto
    /net
    /node
        /service
        /wallet
    /system
    /tui
    /tx
    /util
        /rpc
    /zk

/bin
    /cashierd
    /darkfid
    /drk
    /ircd
    /map
```

there are a few outliers that were not considered in the plans above, in particular:

```
/src 
    /tui
    /cli
/bin 
    /map
```

any preferences on what to do with them?
