### ISSUE TITLE
Use anyhow crate for Results in applications/sw. 

### ISSUE THREAD

**Issue by parazyd** [darkrenaissance/darkfi#41]
We should just switch to using `anyhow` https://docs.rs/anyhow/ for our error types and remove redundant error code
that just pollutes the codebase.

This is blocked until we upgrade to the latest Halo2 crate revision.

**Comment by ghassmo** [comment]
@parazyd are you suggesting removing the error.rs file and just using anyhow crate ?

**Comment by parazyd** [comment]
@ghassmo Not completely. We should keep our own errors, but all of these wrappers for existing
errors from other crates can just be removed.

**Comment by ghassmo** [comment]
yes it's good idea

**Comment by narodnik** [comment]
https://www.sheshbabu.com/posts/rust-error-handling/
See the section called "Applications vs Libraries"

Library code uses our own internal error. Application code uses anyhow.
