### ISSUE TITLE
Can't parse configuration after install

### ISSUE THREAD

**Issue by jkhales** [darkrenaissance/darkfi#5]
Followed https://github.com/darkrenaissance/darkfi/blob/master/doc/tutorial.md

Using OSX Big Sur

<img width="515" alt="Screen Shot 2021-10-21 at 7 10 29 AM" src="https://user-images.githubusercontent.com/1220444/138295119-13e89dd5-a3d7-421d-98b8-682e244182d2.png">

**Comment by ethermachine** [comment]
@ghassmo

`make: Nothing to be done for `all'.`

**Comment by itsvetobaby** [comment]
@ghassmo on big sur too with the same issue, if i interpreted the above correctly the correct place for the binaries is usr/local/bin which is where i got them, but i get the error
```
Could not parse configuration
Please follow the instructions in the README
Error: ConfigNotFound

```
