### ISSUE TITLE
Subsistute references of "liberalism" with "neo-liberalism", in Documentation

### ISSUE THREAD

**Issue by irelativism** [darkrenaissance/darkfi#56]
References of Liberalism in documentation in Ideology section at https://darkrenaissance.github.io/darkfi/IDEOLOGY.html should be replaced with Neo-Liberalism.

Liberalism in its theoretical from has quite a diferent implementation to what we have assisted with the ravages of Neo-Liberalism on our society.

Cheers irelativism

**Comment by lunar-mining** [comment]
ideology.md is an extract from Ocalan's Manifesto for a Democratic Civlization Vol. 3. I wouldn't be comfortable changing its meaning unless we believe it is a translation error from the original Turkish.

Unless someone can provide evidence of Liberalism being a mistranslation, I will close this issue.

**Comment by irelativism** [comment]
this is a good reference for what is decribed https://oxfordre.com/communication/view/10.1093/acrefore/9780190228613.001.0001/acrefore-9780190228613-e-176, regarding changes the text already diverges quite a bit from original so if it helps with a better comprenssion of the message I think this bug fix would be usefull for all people involved in darkfi project. Not to speak about the evident roots of liberalism theory from the spanish anarchist movements, specifically anarcho-syndichalism thought. Cheers Irelativism

**Comment by narodnik** [comment]
We cannot change the text unless it's a mistranslation. If you find the original text in Kurdish, I will verify for you the correct spelling.

**Comment by irelativism** [comment]
it is a mistranlation :s the reference here is for neoliberalism not the theory of liberalism @lunar-mining , read resouce provided above.

**Comment by narodnik** [comment]
OK show us the paragraphs in Turkish (or Kurdish)

**Comment by irelativism** [comment]
you can do it yourself Im just reporting the mistake, so this issue should not be closed given, problem is still stsnding ;) Cheers
