### ISSUE TITLE
Look into filtering specific targets in logging system

### ISSUE THREAD

**Issue by narodnik** [darkrenaissance/darkfi#58]
All the log commands have a target argument which allows us to create specific logger messages per submodule, such as:

```rust
debug!(target: "net", "very noisy messages");
```

I want be able to only allow or disallow messages from the "net" target in the logging system.

The problem is more acute with the trace level logging which includes a ton of random system messages. I want to filter all of them and just show trace log messages from the net target.

Please edit `bin/ircd/src/main.rs` `main()` as necessary.

**Comment by Dastan-glitch** [comment]
Ok, this is done using `add_filter_allow` on `ConfigBuilder` like this:
```
let config = ConfigBuilder::new()
        .add_filter_allow("net".to_string())
        .build();
```
then passing `config` to `TermLogger::init`
but I'm not sure what you mean by random system messages at trace level

**Comment by parazyd** [comment]
@Dastan-glitch Hey! So the most proper way to do this would be through an env var.
You can do something like this:

```rust
fn main() {
    let log_config = match env::var_os("LOG_TARGETS") {
        Some(x) => simplelog::ConfigBuilder::new()
            .add_filter_allow("net".to_string())
            .build(),
        None => simplelog::Config::default(),
    };

    TermLogger::init(
        LevelFilter::Debug,
        log_config,
        TerminalMode::Mixed,
        ColorChoice::Auto,
    )
    .unwrap();

    debug!(target: "net", "foo net");
    debug!(target: "zk", "foo zk");
}
```

So you would run it:

```shell
$ LOG_TARGETS=net ./my_command
$ LOG_TARGETS=net,zk,something,foo,bar ./my_command
```

**Comment by Dastan-glitch** [comment]
Nice, I was trying something similar but this is much better, I'll add env var for `LevelFilter` for `Debug` and `Trace` and create a PR

**Comment by Dastan-glitch** [comment]
This one only has `Debug` https://github.com/darkrenaissance/darkfi/blob/3f8768ee69023592275eeef9b1617f2ac3a59369/bin/ircd/src/main.rs#L250
