### ISSUE TITLE
DarkFi website down

### ISSUE THREAD

**Issue by sptnkp** [darkrenaissance/darkfi#71]
The website mentioned here is not active. I am unable to ping the website. (tested through both my home network and TOR to rule out the possibility of it being blocked)

The matrix instance is also not reachable.

**Comment by irelativism** [comment]
Indeed has been down for 2 days now. Maybe gvornment enforcement you never know, A good lesson to host your own servers and never outsource such I guess. If you want to get a hold of people involved, you can reach them through https://polytech.barcelona/ most people in that project are involved here as well @sptnkp ;).
