### ISSUE TITLE
Suggestion: Brew formula

### ISSUE THREAD

**Issue by SubGlitch1** [darkrenaissance/darkfi#79]
It is kind of a pain to install this on mac as a lot of the dependencies have different names (mostly minor abrevations). So it would be nice to make this a brew formula so they install automatically with darkfi. I would create a pull request but this must be done by the package container. Alternatively i could write a setup script for mac which installs the dependencies.

**Comment by parazyd** [comment]
Hey. A PR would be welcome. You could also update the README table with the valid dependency names.
