### ISSUE TITLE
Matrix chatroom

### ISSUE THREAD

**Issue by silverpill** [darkrenaissance/darkfi#81]
Just seen this https://twitter.com/DarkFiSquad/status/1532695225252077568
I'd like to remind that I have admin powers in the main matrix chatroom (dev) and I can make it accessible again from another server (matrix rooms are decentralized and chat history is replicated to all participating servers). In fact I already did it, the new alias is [#darkfi:poa.st](https://matrix.to/#/#darkfi:poa.st).
You don't need to wait for your server to be back online, just register a new account on any other matrix server and join the room.

**Comment by narodnik** [comment]
Thanks a lot. I just tried to sign up to poa.st but it looks like a fediverse instance. How can I access matrix with them? Or do you recommend some other matrix server? thanks

**Comment by silverpill** [comment]
@narodnik poa.st matrix server is https://matrix.poa.st/, they also have element-web at the same domain. It has good uptime, though it's primarily intended for poa.st users.
More recommendations here: https://glowers.club/wiki/doku.php?id=wiki:homeservers

**Comment by silverpill** [comment]
@narodnik Your account on poa.st was accidentally deactivated during bot cleanup. I asked admin about restoring it and he said it's possible but requires password reset. If you send him email to graf(at)poast.org he will send you a new password.
Alternatively, you can register on another server e.g. https://halogen.chat/

**Comment by narodnik** [comment]
Thank you! Will get around to that
