### ISSUE TITLE
make issue

### ISSUE THREAD

**Issue by KeithAlice** [darkrenaissance/darkfi#89]
How to solve below issue?

   Compiling darkfi v0.3.0 (/home/test/darkfi)
error[E0599]: the method `as_display` exists for reference `&std::io::ErrorKind`, but its trait bounds were not satisfied
   --> src/error.rs:273:13
    |
273 |       #[error("IO error: {0}")]
    |               ^^^^^^^^^^^^^^^ method cannot be called on `&std::io::ErrorKind` due to unsatisfied trait bounds
    |
    = note: the following trait bounds were not satisfied:
            `std::io::ErrorKind: std::fmt::Display`
            which is required by `&std::io::ErrorKind: DisplayAsDisplay`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `darkfi` due to previous error
Makefile:30: recipe for target 'ircd' failed
make: *** [ircd] Error 101

**Comment by ghassmo** [comment]
Hello @KeithAlice, it's probably because of the old rust version installed on your os.
Please run this command to update:
`$ rustup update`

**Comment by KeithAlice** [comment]
yes, it works now. thx
