### ISSUE TITLE
Check that the cryptography used is sufficiently quantum secure.

### ISSUE THREAD

**Issue by spital** [darkrenaissance/darkfi#90]
Investigating and/or ensuring the security of the cryptography used in light of recent planned developments in quantum computing.
IBM plans to have more than 4,000 qubits of quantum system by 2025. It's more complicated than that, see for yourself:

Expanding the IBM Quantum roadmap to anticipate the future of quantum-centric supercomputing
 (10 May 2022)
https://research.ibm.com/blog/ibm-quantum-roadmap-2025

**Comment by narodnik** [comment]
It's not quantum secure. Not our focus right now. Quantum computers will have a decade before becoming an issue.
