### ISSUE TITLE
Error compiling on Mac big sur

### ISSUE THREAD

**Issue by scicourse** [darkrenaissance/darkfi#97]
I'm getting the following error compiling this on Mac big sur.
Rustup version 1.24.3

error[E0599]: the method as_display exists for reference &std::io::ErrorKind, but its trait bounds were not satisfied
   --> src/error.rs:265:13
    |
265 |       #[error("IO error: {0}")]
    |               ^^^^^^^^^^^^^^^ method cannot be called on &std::io::ErrorKind due to unsatisfied trait bounds
    |
    = note: the following trait bounds were not satisfied:
            std::io::ErrorKind: std::fmt::Display
            which is required by &std::io::ErrorKind: DisplayAsDisplay

For more information about this error, try rustc --explain E0599.

**Comment by ghassmo** [comment]
Hello @scicourse,
Please first update rust version on your OS by running this command:
$ rustup update
then try again
